---
- template: src=hadoop.conf dest="{{ hibench_home }}/conf/hadoop.conf" owner=root group=root

- name: Replace variables of {{ hibench_home }}/bin/build_all.sh
  lineinfile: dest="{{ hibench_home }}/bin/build-all.sh" regexp='mvn clean package' line="mvn -Phadoopbench -Dspark=2.1 -Dscala=2.11 clean package"
  #configiure environment variables
