---
# RedHat related OSs
- name: Yum install {{ item }}
  yum:
    name={{ item }} state=installed
  when: "ansible_os_family == 'RedHat'"
  with_items:
  - bc
  - tar

# Debian related OSs
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  with_items:
  - bc
  - tar
  - openjdk-8-jdk

- name: Git clone Hibench from github
  git: repo=https://github.com/intel-hadoop/HiBench.git dest={{ hibench_home }} version={{ hibench_version }} 
  register: result
  until: result|success
  retries: 1
  delay: 2

#- file: dest={{ hibench_home }} src=/opt/hibench-{{ hibench_version }} state=link
#- file: dest={{ hibench_home }} src={{ maven_decompress }} state=link
#  tags:
#    - hilink

