---
# tasks file for ansible-role-hibenchi/
## hibench install and configure 
- stat: path={{ hibench_home }}
  register: hibench_installed
  tags:
    - m1

- include: install.yml
  when: not hibench_installed.stat.exists
  tags:
    - m2

- include: configure.yml
  when: not hibench_installed.stat.exists
  tags:
    - m3

#- name: Execute the command ./bin/build_all.sh, build hibench
#  shell: ./build_all.sh
#  args: 
#    chdir={{ hibench_home }}/bin
#  tags:
#    - m4
