---
# tasks file for ansible-role-hibench/
- stat: path={{ hibench_home }}
  register: hibench_installed

- include: install.yml
#  when: not hibench_installed.stat.exists

- include: configure.yml

- name: Execute the command ./bin/build_all.sh, build hibench
  shell: ./build_all.sh
  args: 
    chdir={{ hibench_home }}/bin
  tags:
    - build
